<?php

define('PERMISSIONS',

[
	'view_home',
	'view_admin_area',
	'view_categories',
	'add_categories',
	'edit_categories',
	'delete_categories',
	'view_permissions',
	'grant_permissions',
	'add_permissions',
	'edit_permissions',
	'delete_permissions',
	'view_roles',
	'assign_roles',
	'add_roles',
	'edit_roles',
	'delete_roles',
	'edit_slider_images',
	'view_dashboard',
	'view_sales',
	'edit_sales',
	'delete_sales',
	'add_marital_status',
	'view_marital_status',
	'edit_marital_status',
	'delete_marital_status',
	'delete_user',
	'edit_user',
	'join_welfare',
	'view_welfare_members',
	'edit_welfare_members',
	'add_contribution',
	'delete_contribution',
	'view_contribution',
	'edit_contribution',
	'view_position',
	'add_position',
	'edit_position',
	'delete_position',

	
]);